### PR TITLE
Handle java source/target defined at extension level

### LINKED ISSUE #3721: 'Type Pattern' being reported as an error even though Java source level is above 16
While modding for the game Mindustry, I noticed that I get the error `The Java feature 'Type Patterns' is only available with source level 16 and above - Java(4195411)` while doing 'Type Pattern' even though the `sourceLevel` is set to 17 (see linked mod template repository down below).
The explanation for this error might be because `targetLevel` is set to 8 and the `--release 8` argument is also added. If you are wondering why it is like that... I do not know but one of the dependecy, `jabel` (https://github.com/Anuken/jabel), is supposed to make the Java 17 features be retro compatible with Java 8.

##### Environment
- Operating System: Windows 11
- JDK version: OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)
- Visual Studio Code version: 1.91.1
- Java extension version: 1.33.2024072008

##### Steps To Reproduce
1. Clone https://github.com/Anuken/MindustryJavaModTemplate
2. Add (anywhere) some simple Type Pattern cast (e.g. below)
```java
Object test = 2f;
if (test instanceof Float f) {

}
```
3. Try to build using `gradle jar` or `./grawled jar`, it should be succesful.

##### Current Result
The 'Type Pattern' are being reported as an error, even though it builds fine (and run fine in-game too, but I don't expect you to bother trying.)

##### Expected Result
The 'Type Pattern' to not be reported as an error, or at least be able to ignore the error.

##### Additional Informations
Due to the specific situation, it might not be possible to fix this, so maybe adding the option to ignore error is a possible way if it's possible for you to do.

### PR DESCRIPTION
**Pull request by Arthurm1**
This will take into account the `java plugin` source/target compatibility settings.
e.g. using...
```
java {
  targetCompatibility = JavaVersion.VERSION_1_8
  sourceCompatibility = JavaVersion.VERSION_1_9
}
```
instead of
```
tasks.withType(JavaCompile) {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_9
}
```

I'm not sure if this is enough to fix https://github.com/redhat-developer/vscode-java/issues/3721.  The source/target compatibility in `JVMBuildTarget` will have changed but the javac options will still contain `--release 8`.  Hopefully that will be ok for the eclipse settings.

I note that [here](https://github.com/bsideup/jabel) it says to configure the `compileJava` task with source/target and not the `java` plugin when using `Jabel`

I've also extended the `POJO` constructor copying used in `DefaultSourceSets` to the language extensions.  It's not needed for normal running but it's a pain when debugging as all the variables/watches just show the proxy classes.

### CODE REVIEW

**Comment by jdneo** [comment]
> I've also extended the POJO constructor copying used in DefaultSourceSets to the language extensions. It's not needed for normal running but it's a pain when debugging as all the variables/watches just show the proxy classes.

There is an issue about this: https://github.com/microsoft/build-server-for-gradle/issues/175. I also did some investigation and turns out the copy constructor is not needed for running.

I'm thinking that, for debugging purpose, maybe override `toString()` is a better approach than using the copy constructor?

-----

Update:

The copy constructor is required. If we remove all the copy constructor, here:

https://github.com/microsoft/build-server-for-gradle/blob/395b97757da8d0d82bc2c68c4aca4331bea4e584/model/src/main/java/com/microsoft/java/bs/gradle/model/actions/GetSourceSetsAction.java#L174

The sourceset is a proxy wrapperred type, and it will encounter some problem 

image

File: plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java [hunk 1]
```diff
@@ -69,6 +73,37 @@ public DefaultJavaExtension getExtensionFor(Project project, SourceSet sourceSet
       extension.setCompilerArgs(compilerArgs);
       extension.setSourceCompatibility(getSourceCompatibility(compilerArgs));
       extension.setTargetCompatibility(getTargetCompatibility(compilerArgs));
+
+      // it's possible to set source/target compatibility in different places.
+      // Java plugin setting should override javacoptions
+      JavaVersion sourceVersion = null;
+      JavaVersion targetVersion = null;
+      if (GradleVersion.current().compareTo(GradleVersion.version("7.1")) >= 0) {
```
Comment (jdneo) [inline plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java]: What the difference between getting the source/target level from the java plugin and 

```
JavaCompile .getSourceCompatibility();
JavaCompile .getTargetCompatibility();
```
?

Comment (Arthurm1) [reply plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java]: I'd like to know too 😆 

The code managing it is [here](https://github.com/gradle/gradle/blob/dd40c5b0e06bef621941984ed8ba565dbec06805/platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java#L327)

I think that Gradle takes any source/target compatibility the user has set for the `java` plugin and applies it to the compiler task.  And then takes the compiler task settings and applies that to javacoptions.

But any of these can be set by the user in the build file and they can clash and Gradle seems fine with that.
They can also be illegal i.e. javacoptions require `target` >= `source` but it works out because the user has also specified `--release` in the options and that takes precedence.

I guess ultimately Gradle is just feeding all these settings into javacoptions but Intellij and Eclipse want the source/target compatibility for their own compilation settings and they seem to take that from the plugin or compiler settings rather than the javacoptions.

`Jabel` also seems to be taking advantage of this and using the source/target compatibility settings even though `--release` is set.

**Comment by Arthurm1** [comment]
> The copy constructor is required. If we remove all the copy constructor, here:

Shall I leave my changes to `DefaultJavaExtension`/`DefaultScalaExtension` then or do you want them gone?

**Comment by jdneo** [comment]
> Shall I leave my changes to DefaultJavaExtension/DefaultScalaExtension

I think you can leave as it is. Until we find a way to get rid of the copy constructor entirely

File: plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java (hunk 1 above)
Comment (jdneo) [reply plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java]: I'll file a ticket at gradle for the recommended way to get the source/target level

**Comment by jdneo** [comment]
@Arthurm1

I think we should use `javaCompile.getSourceCompatibility()` and `javaCompile.getTargetCompatibility()`.

AFAIK, there are three different kind of ways to set the source/target level.

1.
```
java {
  targetCompatibility = JavaVersion.VERSION_1_8
  sourceCompatibility = JavaVersion.VERSION_1_9
}
```

2.
```
tasks.withType(JavaCompile) {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_9
}
```

3.
```
sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_9
```

The current approach cannot get the version in case 2. While using the `JavaCompile` instance can cover all three cases.

Considering `JavaCompile` is official API which no need to use reflection, I prefer to use it directly.

**Comment by jdneo** [comment]
Hi @Arthurm1, would you like to update the PR?

Or do you have any concern about `javaCompile.getSourceCompatibility()` and `javaCompile.getTargetCompatibility()`

**Comment by Arthurm1** [comment]
@jdneo Will look at it this weekend and probably change the PR

**Comment by jdneo** [comment]
@Arthurm1 Thank you.

My thought is that we can just simply get the source/target level from JavaCompile, no need to inspecting from compile args. (Correct me if this is working for any cases)

**Comment by Arthurm1** [comment]
@jdneo I've changed it so that the source/target compatibility is populated purely from the `JavaCompile` task.  `JavacOptions` are still passed back for BSP but they are ignored for compatibility settings.

This seems to reflect more how people use the Gradle settings, i.e. set source/target compatibility in `JavaCompile` for IDE usage and the `JavacOptions` for jar and release.

File: plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java [hunk 2]
```diff
@@ -67,8 +66,10 @@ public DefaultJavaExtension getExtensionFor(Project project, SourceSet sourceSet
 
       List<String> compilerArgs = getCompilerArgs(javaCompile);
       extension.setCompilerArgs(compilerArgs);
-      extension.setSourceCompatibility(getSourceCompatibility(compilerArgs));
```
Comment (jdneo) [inline plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java:70]: What about `getSourceCompatibility()` && `getTargetCompatibility()`. Will you consider to remove it as well? Since I believe they are not used now.

Comment (jdneo) [reply plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java:70]: @Arthurm1, are you feel ok to remove these unused methods? If yes, I can append a commit to the PR and merge it.

Comment (Arthurm1) [reply plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java:70]: Which ones do you mean?  `JvmBuildTargetEx.getTargetCompatibility()`?  Is that no longer used?

Or do you mean `JavaLanguageModelBuilder.getTargetCompatibility(List<String> compilerArgs)` should be removed?  ~That's a copy of what Gradle does [here](https://github.com/gradle/gradle/blob/dbd2232425b245f077cacb58b9c5acbc1690511e/platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L143).  It looks like we should probably add more option handling from the Gradle code.~ Wrong link.
That's a copy of what Gradle does [here](https://github.com/gradle/gradle/blob/d4cc98c931d8e0972d2fc4ad03f7c5a186c2d37e/platforms/jvm/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L295)

Comment (jdneo) [reply plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/JavaLanguageModelBuilder.java:70]: Sorry, my bad. I was not aware that they are used when parsing the compiler args.

**Review by jdneo — APPROVED** [review]

**Comment by jdneo** [comment]
Thank you @Arthurm1
